export const restaurantsAr = [
    {
        id: '1',
        name: 'مأكولات بحرية شهية',
        src: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: '2',
        name: 'أطباق لذيذة في مطعم',
        src: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: '3',
        name: 'بيسترو مع مقبلات شهية',
        src: 'https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80',
    },
];
export const restaurantPlansAr = [
    {
        id: '1',
        restaurant_id: ['1', '2', '3', '4'],
        name: 'تجربة جو ممتعة',
        carbs: '120 كربوهيدرات',
        description: 'مأكولات شهية في أجواء مريحة.',
        src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: '2',
        restaurant_id: ['1', '2', '3', '4'],
        name: 'نكهات العالم - خطة مغامرة طهي',
        carbs: '120 كربوهيدرات',
        description: 'نكهات ممتازة بلمسة عصرية.',
        src: 'https://images.unsplash.com/photo-1503392968123-ceabe9e5e630?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1929&q=80',
    },
    {
        id: '3',
        restaurant_id: ['1', '2', '4'],
        name: 'تصوغ ثقافي للمأكولات',
        carbs: '120 سعرة حرارية',
        description: 'تصوغ للطعم والثقافة.',
        src: 'https://images.unsplash.com/photo-1641893728260-19493532d6b9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2022&q=80',
    },
    {
        id: '4',
        restaurant_id: ['1', '4', '3'],
        name: 'أطباق راقية',
        carbs: '120 بروتين',
        description: 'نكهات ممتازة بلمسة عصرية.',
        src: 'https://images.unsplash.com/photo-1562436260-8c9216eeb703?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1941&q=80',
    },
];

export const weekdaysAr = [
    {
        id: '1',
        day: 'الاثنين',
        date: '1',
        month: 'مايو',
        off: false,
        lock: true,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '2',
        day: 'الثلاثاء',
        date: '2',
        month: 'مايو',
        off: false,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '3',
        day: 'الأربعاء',
        date: '3',
        month: 'مايو',
        off: false,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '4',
        day: 'الخميس',
        date: '4',
        month: 'مايو',
        off: false,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '5',
        day: 'الجمعة',
        date: '5',
        month: 'مايو',
        off: true,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '6',
        day: 'السبت',
        date: '6',
        month: 'مايو',
        off: false,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
    {
        id: '7',
        day: 'الأحد',
        date: '7',
        month: 'مايو',
        off: true,
        lock: false,
        plan_id: ['1', '2', '3', '4'],
    },
];

export const mealsAr = [
    {
        id: '1',
        name: 'وجبة الإفطار',
        day_id: ['1', '2', '3', '4'],
        plan_id: ['1'],
    },
    {
        id: '2',
        name: 'وجبة الغداء',
        day_id: ['1', '2', '3', '4'],
        plan_id: ['2', '3', '4', '5'],
    },
    {
        id: '3',
        name: 'وجبة العشاء',
        day_id: ['1', '2', '3', '4'],
        plan_id: ['1', '2', '3', '4', '5'],
    },
    {
        id: '4',
        name: 'وجبة خفيفة',
        day_id: ['1', '2', '3', '4'],
        plan_id: ['1', '2', '3', '4', '5'],
    },
];

export const foodsAr = [
    {
        id: '1',
        src: 'https://images.unsplash.com/photo-1598214886806-c87b84b7078b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80',
        name: 'شهي ومشوي لذيذ',
        description: 'طبق لذيذ يحتوي على نكهات مذهلة.',
        macros: [
            { id: '123', name: 'السعرات الحرارية', amount: '112' },
            { id: '124', name: 'البروتين', amount: '131' },
            { id: '125', name: 'الكربوهيدرات', amount: '120' },
            { id: '126', name: 'الدهون', amount: '126' },
        ],
        meal_id: ['1'],
        day_id: ['1', '2', '3', '4', '5', '6', '7'],
    },
    {
        id: '2',
        src: 'https://images.unsplash.com/photo-1515036918611-4b7f32b8406c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
        name: 'شهي ومشوي لذيذ من السلمون',
        description: 'شرائح لحم مشوية بنكهة رائعة مع جانب من الثوم المسلوق بالزبدة والبطاطس المهروسة.',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['2'],
        day_id: ['1', '2', '3', '4', '5', '6', '7'],
    },
    {
        id: '3',
        src: 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        name: 'طبق شهي آخر',
        description: 'وجبة لذيذة تشبع رغباتك.',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['3'],
        day_id: ['1', '2', '3', '4', '5', '6', '7'],
    },
    {
        id: '4',
        src: 'https://images.unsplash.com/photo-1543826173-70651703c5a4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2079&q=80',
        name: 'طبق لذيذ من السلمون',
        description: 'وجبة لذيذة تشبع رغباتك.',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['4'],
        day_id: ['1', '2', '3', '4', '5', '6', '7'],
    },
    {
        id: '5',
        src: 'https://images.unsplash.com/photo-1598214886806-c87b84b7078b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80',
        name: 'لذيذ ومشوي من السلمون',
        description: 'طبق لذيذ يحتوي على نكهات مذهلة.',
        macros: [
            { id: '123', name: 'السعرات الحرارية', amount: '112' },
            { id: '124', name: 'البروتين', amount: '131' },
            { id: '125', name: 'الكربوهيدرات', amount: '120' },
            { id: '126', name: 'الدهون', amount: '126' },
        ],
        meal_id: ['1', '2', '3', '4'],
        day_id: ['2', '3'],
    },
    {
        id: '6',
        src: 'https://images.unsplash.com/photo-1515036918611-4b7f32b8406c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
        name: 'لذيذ ومشوي من السلمون',
        description: 'شريحة لحم مع الثوم المحمص بالزبدة والبطاطس المهروسة',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['1', '3'],
        day_id: ['2'],
    },
    {
        id: '7',
        src: 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        name: 'طبق لذيذ آخر',
        description: 'وجبة لذيذة تشبع رغباتك.',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['3'],
        day_id: ['2'],
    },
    {
        id: '8',
        src: 'https://images.unsplash.com/photo-1543826173-70651703c5a4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2079&q=80',
        name: 'طبق لذيذ من السلمون',
        description: 'وجبة لذيذة تشبع رغباتك.',
        macros: [
            { id: '127', name: 'السعرات الحرارية', amount: '150' },
            { id: '128', name: 'البروتين', amount: '90' },
            { id: '129', name: 'الكربوهيدرات', amount: '85' },
            { id: '130', name: 'الدهون', amount: '75' },
        ],
        meal_id: ['2', '4'],
        day_id: ['3'],
    },
];
