export const days = [
    {
        id: '0',
        selected: false,
        monthAr: 'نوفمبر',
        dayAr: 'الاثنين',
        month: 'Nov',
        day: 'Mon',
        date: '1',
        locked: true,
    },
    { id: '1', selected: false, monthAr: 'ديسمبر', dayAr: 'الثلاثاء', month: 'Dec', day: 'Tue', date: '2' },
    { id: '2', selected: false, monthAr: 'يناير', dayAr: 'الاربعاء', month: 'Jan', day: 'Wed', date: '3' },
    { id: '3', selected: true, monthAr: 'فبراير', dayAr: 'الخميس', month: 'Feb', day: 'Thr', date: '4' },
    {
        id: '4',
        selected: false,
        monthAr: 'مارس',
        dayAr: 'الجمعة',
        month: 'Mar',
        day: 'Fri',
        date: '5',
        off: 'off',
        offAr: 'راحة',
    },
    { id: '5', selected: false, monthAr: 'ابريل', dayAr: 'السبت', month: 'Apr', day: 'Sat', date: '6' },
    { id: '6', selected: false, monthAr: 'مايو', dayAr: 'الاحد', month: 'May', day: 'Sun', date: '7' },
    { id: '3', selected: false, monthAr: 'يونيو', dayAr: 'الخميس', month: 'Jun', day: 'Thr', date: '4' },
    {
        id: '4',
        selected: false,
        monthAr: 'يوليو',
        dayAr: 'الجمعة',
        month: 'July',
        day: 'Fri',
        date: '5',
        off: 'off',
    },
    { id: '5', selected: false, monthAr: 'اغسطس', dayAr: 'السبت', month: 'Aug', day: 'Sat', date: '6' },
    { id: '6', selected: false, monthAr: 'سبتمبر', dayAr: 'الاحد', month: 'Sep', day: 'Sun', date: '7' },
    { id: '6', selected: false, monthAr: 'اكتوبر', dayAr: 'الاحد', month: 'Oct', day: 'Sun', date: '7' },
];

export const foods = [
    {
        id: '11',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '12',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '13',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '14',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '15',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '16',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '17',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
    {
        id: '18',
        selected: false,
        macros: [
            { label: 'Cal', labelAr: 'سعرات', count: 12 },
            { label: 'Prot', labelAr: 'بروتين ', count: 32 },
            { label: 'Carb', labelAr: 'كارب ', count: 23 },
            { label: 'Fat', labelAr: 'دهون ', count: 23 },
        ],
    },
];
export const meals = [
    {
        selected: true,
        id: '0',
        label: 'Breakfast',
        labelAr: 'ريوق',
    },
    {
        selected: false,
        id: '1',
        label: 'Lunch',
        labelAr: 'غدا',
    },
    {
        selected: false,
        id: '2',
        label: 'Dinner',
        labelAr: 'عشا',
    },
    // {
    //     selected: false,
    //     id: '3',
    //     label: 'Breakfast 2',
    //     labelAr: 'ريوق ٢',
    // },
    // {
    //     selected: false,
    //     id: '4',
    //     label: 'Lunch',
    //     labelAr: 'غدا',
    // },
    // {
    //     selected: false,
    //     id: '5',
    //     label: 'Lunch 2',
    //     labelAr: 'غدا ٢',
    // },
    // {
    //     selected: false,
    //     id: '6',
    //     label: 'Dinner',
    //     labelAr: 'عشا',
    // },
    // {
    //     selected: false,
    //     id: '7',
    //     label: 'Dinner 2',
    //     labelAr: 'عشا ٢',
    // },
    // {
    //     selected: false,
    //     id: '8',
    //     label: 'Meal 1',
    //     labelAr: 'وجبة',
    // },
    // {
    //     selected: false,
    //     id: '9',
    //     label: 'Meal 2',
    //     labelAr: 'وجبة ٢',
    // },
    // {
    //     selected: false,
    //     id: '10',
    //     label: 'Meal 3',
    //     labelAr: 'وجبة ٣',
    // },
    // {
    //     selected: false,
    //     id: '11',
    //     label: 'Meal 4',
    //     labelAr: 'وجبة ٤',
    // },
    // {
    //     selected: false,
    //     id: '12',
    //     label: 'Meal 5',
    //     labelAr: 'وجبة ٥',
    // },
    // {
    //     selected: false,
    //     id: '13',
    //     label: 'Snack',
    //     labelAr: 'سناك',
    // },
    // {
    //     selected: false,
    //     id: '14',
    //     label: 'Snack 2',
    //     labelAr: 'سناك ٢',
    // },
    // {
    //     selected: false,
    //     id: '15',
    //     label: 'Snack 3',
    //     labelAr: 'سناك ٣',
    // },
    // {
    //     selected: false,
    //     id: '16',
    //     label: 'Soup',
    //     labelAr: 'شوربة',
    // },
    // {
    //     selected: false,
    //     id: '17',
    //     label: 'Drinks',
    //     labelAr: 'مشروبات',
    // },
    // {
    //     selected: false,
    //     id: '18',
    //     label: 'Salad',
    //     labelAr: 'سلطة',
    // },
];
